---
- name: restart MySQL (with service)
  service:
    name: MySQL
    state: restarted
  listen: "restart MySQL"
  when: ansible_service_mgr != 'systemd'

- name: restart MySQL (with systemd)
  systemd:
    name: MySQL
    state: restarted
  listen: "restart MySQL"
  when: ansible_service_mgr == 'systemd'